spring.application.name=fenixtech
server.servlet.context-path=/fenixtech/api/v1

spring.datasource.url=jdbc:mariadb://mariadb:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf8mb4
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

api.security.token.secret=${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyPleaseChangeInProduction}
api.security.token.expiration=${JWT_EXPIRATION:86400000}

spring.mail.host=${HOST_MAIL}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Reintenta la conexión si falla al arrancar
spring.datasource.hikari.initialization-fail-timeout=60000
# Tiempo de espera para obtener una conexión
spring.datasource.hikari.connection-timeout=30000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

server.tomcat.max-parameter-count=1000
server.tomcat.max-part-count=1000